# Application Configuration - Version 1
app:
  name: "MyApp"
  version: "1.0.0"
  environment: "production"
  
database:
  host: "localhost"
  port: 5432
  username: "admin"
  password: "secret123"
  database_name: "myapp_db"
  
features:
  - authentication
  - logging
  - caching
  
settings:
  timeout: 30
  retry_attempts: 3
  debug_mode: false
  
servers:
  web:
    host: "0.0.0.0"
    port: 8080
  api:
    host: "0.0.0.0"
    port: 8081

